### ISSUE TITLE
[Bug]: Error when downloading any model after updating to 3.3.0

### ISSUE THREAD

**Issue by Terroosh** [BlafKing/sd-civitai-browser-plus#189]
### Describe the bug.

After updating to 3.3.0 any download action fails

### Steps to reproduce the problem.

1. Download any model
2. Error occurs 

### Expected behavior

Model is downloaded

### System info

* Extension version: 3.3.0
* OS: Win11
* SD-WebUI version: 1.6
* Python: 3.10.6

### Console logs

```Shell
File "K:\SD A1111\extensions\sd-civitai-browser-plus\scripts\civitai_download.py", line 500, in download_file_old
    with open(file_path, "ab", encoding="utf-8") as f:
ValueError: binary mode doesn't take an encoding argument
```

**Comment by BlafKing** [comment]
Thanks for reporting!

I only tested Aria2 and forgot to test the other download method, this was a very easy fix so I've published a quick hotfix, thanks for bringing it to my attention!

**Comment by Terroosh** [comment]
> Thanks for reporting!
> 
> I only tested Aria2 and forgot to test the other download method, this was a very easy fix so I've published a quick hotfix, thanks for bringing it to my attention!

Speaking of Aria2, I noticed the exe still gets launched at SD startup even if "Download models using Aria2" is unchecked. Is this something that can be changed or was it done like that so people wouldn't have to restart the ui?
