### ISSUE TITLE
[Bug]: activation text stopped working due to two json files

### ISSUE THREAD

**Issue by onyxlee** [BlafKing/sd-civitai-browser-plus#270]
### Describe the bug.

Now the extension creates two json files: the abc.safetensors will be associated with both abc.json and abc.safetensors.json. The first file has modelId & sha256, the second file has activation text and description, sd version. So now when you load a lora or anything, the activation text doesn't automatically load in the prompt.
I downloaded lots of loras with this issue. Either your future update can read both json, or can combine them into one and remove the extra one. Otherwise it's extremely inconvenient to use any lora.
Thank you.

### Steps to reproduce the problem.

My suspicion is: maybe when downloading lora in a batch, this issue will happen.

1. Go to the lora folder, open two json files, the abc.safetensors will be associated with both abc.json and abc.safetensors.json
2. when you load a lora or anything, the activation text doesn't automatically load in the prompt.
3. ...

### Expected behavior

The extension should have loaded both the activation text and the lora file.

### System info

* Extension version: latest
* OS: windows 11
* SD-WebUI version: 1.8.0
* Python:  python: 3.10.11
* torch: 2.1.2+cu121
* xformers: 0.0.23.post1
* gradio: 3.41.2

### Console logs

```Shell
There is no error log, it simply doesn't load activation text.
```

**Comment by BlafKing** [comment]
This issue was present in the previous version, as previously reported in #267

It should already be fixed in the latest version, you can try re installing the latest version if it shows that you already have the latest.

Thanks regardless for reporting, I'll mark this as resolved as the issue should already be solved 👍🏻

**Comment by onyxlee** [comment]
Thank you, I just uninstalled and clean re-installed the extension. The problem still exists. Do I have to delete and then re-download all the loras, or can I ask the extension to rebuild the json files?
Thank you again.
