### ISSUE TITLE
[BUG] Unable to download

### ISSUE THREAD

**Issue by Cmini0n** [BlafKing/sd-civitai-browser-plus#31]
I am new to posting on git hub and this is just a weird issue that started today so was wondering if anyone else was having the issue or if someone new how to fix. When i have checkpoints and hit refresh i get this error..

Traceback (most recent call last):                                                    | 21/120 [00:02<00:09, 10.75it/s]
  File "F:\Art\AI\App\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\Art\AI\App\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\Art\AI\App\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\Art\AI\App\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\Art\AI\App\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\Art\AI\App\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\Art\AI\App\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\Art\AI\App\Automatic1111\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 344, in update_model_list
    HTML = model_list_html(gl.json_data, model_dict, content_type)
  File "F:\Art\AI\App\Automatic1111\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 168, in model_list_html
    if 'baseModel' in item['modelVersions'][0]:
IndexError: list index out of range

is it due to new automatic1111 update or does anyone know a fix for this? I hope i posted this right and any help would be aperciated.

**Comment by BlafKing** [comment]
Thanks for the report!
Not sure exactly why this error is happening, this part of the code searches for the matching Base Model version of the model that is being indexed at that time.
The error suggests it couldn't find a Base Model field for one of the models it was indexing and has thus failed,
I'll add an extra check there that sets the Base Model to "Not Found" if it's not found.

I'm currently working on the next update which is soon finished and I will add this fix to it!

**Comment by Terroosh** [comment]
Came to report the same, looking forward to the next update

**Comment by Cmini0n** [comment]
> Thanks for the report! Not sure exactly why this error is happening, this part of the code searches for the matching Base Model version of the model that is being indexed at that time. The error suggests it couldn't find a Base Model field for one of the models it was indexing and has thus failed, I'll add an extra check there that sets the Base Model to "Not Found" if it's not found.
> 
> I'm currently working on the next update which is soon finished and I will add this fix to it!

tyvm :) i love your extension so much.

**Comment by BlafKing** [comment]
I've just published the update which now inclused this fix, please let me know if it has fixed the error!
If you still have the same error or if something else now breaks, please provide me with the details you inserted when pressing Refresh (like what content type, time period, sort by, search term, search type, tile count, the more info the better!)
I'll then be able to bug test the issue better :)

**Comment by Cmini0n** [comment]
> I've just published the update which now includes this fix, please let me know if it has fixed the error! If you still have the same error or if something else now breaks, please provide me with the details you inserted when pressing Refresh (like what content type, time period, sort by, search term, search type, tile count, checkboxes, etc.) I'll then be able to bug test the issue better :)

that fixed it for me! TYVM for such a fast fix

**Comment by BlafKing** [comment]
glad to hear that fixed the issue!
I'll go ahead and close this thread and mark it as resolved, thanks again for reporting it! :)

**Comment by Cmini0n** [comment]
> glad to hear that fixed the issue! and no worries, luckily it was a very easy fix :) I'll go ahead and close this thread and mark it as resolved, thanks again for reporting it! :)

i should have posted new one but i edited other one, new error, sorry i jumped the gun thinking it fixed it since first page finally loaded. let me try a few things so i can give you more context

**Comment by Cmini0n** [comment]
k so this is what i have gotten so far. if i am on the first page with tile size 14 and tile count 18 ( for some reason i have it saved in settings but it only shows 16), the 2nd page just gives that second error i posted. if i hit next from 2nd page it will load the 3rd page. it will also load the 4th page for me to np. i have it setup on time period week and sort by newest. so either it is some issue atm with the checkpoints on their website. im gonna delete every one i have if i have any from 2nd page i downloaded manually and see if that fixes it and then redownload through your extention.

**Comment by Cmini0n** [comment]
removed every checkpoint i had on page 2 and still doing it. so far after going to 10 pages its only page 2. maybe there is just a checkpoint on there it does not like and want to load

**Comment by BlafKing** [comment]
Thanks for the clarification! I see now that I haven't properly implemented catching the error you posted:
```
if 'baseModel' in item['modelVersions'][0]:
IndexError: list index out of range
```
I also filled in the settings you had and was able to recreate the error, it should now be fixed after the latest hotfix I published just now!

**Comment by Cmini0n** [comment]
> Thanks for the clarification! I see now that I haven't properly implemented catching the error you posted:
> 
> ```
> if 'baseModel' in item['modelVersions'][0]:
> IndexError: list index out of range
> ```
> 
> I also filled in the settings you had and was able to recreate the error, it should now be fixed after the latest hotfix I published just now!

ty, sorry for the fast respone saying it was fixed, i thought it was since first page loaded but then that happened. i will update and let you know

**Comment by Cmini0n** [comment]
> Thanks for the clarification! I see now that I haven't properly implemented catching the error you posted:
> 
> ```
> if 'baseModel' in item['modelVersions'][0]:
> IndexError: list index out of range
> ```
> 
> I also filled in the settings you had and was able to recreate the error, it should now be fixed after the latest hotfix I published just now!

it all works now tyvm! i went  through all 15 pages it displays with those settings ( forgot to tell you i had nsfw content checked to ) but yea everything loads fine now. tysvm! you have a good day and ty again for fixing it so fast. i love your extention.

**Comment by BlafKing** [comment]
No worries at all!
The error is indeed caused by 2 broken models like you suggested, one being "test model" and the other one being "test5"
An error still occurs when you try to select them since they're broken but the page containing broken models does load properly now!
I'll see if I can hide any broken models in the future 👍🏻

**Comment by Cmini0n** [comment]
> No worries at all! Glad to hear you like the extension :) The error is indeed caused by 2 broken models like you suggested, one being "test model" and the other one being "test5" An error still occurs when you try to select them since they're broken but the page containing broken models does load properly now! I'll see if I can hide any broken models in the future 👍🏻

tyvm for fixing and im really sorry to bother you with a new issue. this one was working before update but you cant downoad anything anymore. i tried several checjkpoints and loras and every time i get,

Failed to start download: 'result'
Preview image saved to: F:\Art\AI\App\Automatic1111\stable-diffusion-webui\models\Stable-diffusion\epicrealism_naturalSinRC1VAE.preview.png
Error occured during download of "F:\Art\AI\App\Automatic1111\stable-diffusion-webui\models\Stable-diffusion\epicrealism_naturalSinRC1VAE.safetensors".

sorry to bother you again

**Comment by BlafKing** [comment]
Thanks for notifying me about the issue!
No worries about bothering me, I'll look into it right now :)
I'll rename this thread to make it relevant to the current issue

**Comment by BlafKing** [comment]
Ended up being a very silly issue, took me way too long to figure out haha :,) 
Should be fixed now!

Thanks again for notifying me about the issue so soon! :)

**Comment by Cmini0n** [comment]
> Ended up being a very silly issue, took me way too long to figure out haha :,) Should be fixed now!
> 
> Thanks again for notifying me about the issue so soon! :)

yvw and ty for fixing everything :) everything works now so ty again!
